### ISSUE TITLE
INCOMPRENSIBLE PËRMISSION GUIDE

### ISSUE THREAD

**Issue by Fargus5** [DiscowZombie/UltimateTs#12]
Hey, I've a problem with your permission guide:

you wrote this:

Now, you need to define linked TeamSpeak ranks for your players. The ranks system is baised on permissions. Add this:
Code (Text):
  perms:
    exemplePerms: 10
exemplePerms is your permission and 10 is the ranks to link. In each permissions plugin, all ranks had the permission group.<name of rank> (or rank.<name of rank> depend on your PemissionSystem). Then, to link your ranks, add the permission group.<name of rank> (or rank.<name of rank> depend on your PemissionSystem) and the id of your TeamSpeak ranks.

You can add an infinit numbers of permissions !

Spoiler: Example for my server
Code (Text):
perms:
  group.admin: 7
  group.mod: 9
  group.vip: 10
  mypermission: 12
Admin will get the TeamSpeak rank 7, Mod: 9, VIP: 10 and players with permission "mypermission": 12.

But in the config is totally different.

```
perms:
  myPermission: 7
  group:
    admin: 2
    Gestione: 6
    Amministratore: 39
    Moderatore: 7
    Straniero: 10
  rank:
    admin: 2
    Gestione: 6
  ts:
    gestione: 6
  ultimatets:
    use: 10
```

I really don't understand what to do.

I tried doing
/pex group Gestione add group.Gestione
/pex group Gestione add rank.Gestione
/pex group Gestione add group.Gestione:6
/pex group Gestione add group.Gestione: 6

Anything of this work.

Could u tell me what I need to do?!!! please

tanks
